<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="10" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-10T15:22:39 ICT" name="Suite" finished-at="2022-02-10T15:43:27 ICT" duration-ms="1247807">
    <groups>
    </groups>
    <test started-at="2022-02-10T15:22:39 ICT" name="Test1" finished-at="2022-02-10T15:43:27 ICT" duration-ms="1247807">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:tests.LoginTest@2ea41516]" started-at="2022-02-10T15:22:39 ICT" name="setUp" finished-at="2022-02-10T15:22:42 ICT" duration-ms="3409" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[test1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginWithBlankField()[pri:0, instance:tests.LoginTest@2ea41516]" started-at="2022-02-10T15:22:42 ICT" name="loginWithBlankField" finished-at="2022-02-10T15:22:44 ICT" duration-ms="1171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithBlankField -->
        <test-method signature="loginByAdmin()[pri:0, instance:tests.LoginTest@2ea41516]" started-at="2022-02-10T15:22:44 ICT" name="loginByAdmin" finished-at="2022-02-10T15:22:54 ICT" duration-ms="10845" status="FAIL">
          <exception class="org.awaitility.core.ConditionTimeoutException">
            <message>
              <![CDATA[Condition with tests.LoginTest was not fulfilled within 10 seconds.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.awaitility.core.ConditionTimeoutException: Condition with tests.LoginTest was not fulfilled within 10 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
at tests.LoginTest.loginByAdmin(LoginTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.getCurrentUrl()" because the return value of "tests.LoginTest.getDriver()" is null
at tests.LoginTest.lambda$0(LoginTest.java:39)
at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
... 4 more
]]>
            </full-stacktrace>
          </exception> <!-- org.awaitility.core.ConditionTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginByAdmin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@2ea41516]" started-at="2022-02-10T15:43:26 ICT" name="tearDown" finished-at="2022-02-10T15:43:27 ICT" duration-ms="867" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.InvM_InvoiceListTest">
        <test-method signature="clickInvoiceManagement()[pri:0, instance:tests.InvM_InvoiceListTest@3e11f9e9]" started-at="2022-02-10T15:22:54 ICT" name="clickInvoiceManagement" finished-at="2022-02-10T15:22:55 ICT" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickInvoiceManagement -->
        <test-method signature="laphoadon1dongSuccess()[pri:0, instance:tests.InvM_InvoiceListTest@3e11f9e9]" started-at="2022-02-10T15:22:55 ICT" name="laphoadon1dongSuccess" finished-at="2022-02-10T15:23:35 ICT" duration-ms="39924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laphoadon1dongSuccess -->
        <test-method signature="laphoadonnhieudongSuccess()[pri:0, instance:tests.InvM_InvoiceListTest@3e11f9e9]" started-at="2022-02-10T15:23:35 ICT" name="laphoadonnhieudongSuccess" finished-at="2022-02-10T15:43:26 ICT" duration-ms="1191421" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[SAI O HANG HOA Điện thoại sam sung galaxy a10O HOA DON0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: SAI O HANG HOA Điện thoại sam sung galaxy a10O HOA DON0
at pages.InvM_InvoiceListPage.lapHoaDon(InvM_InvoiceListPage.java:203)
at tests.InvM_InvoiceListTest.laphoadonnhieudongSuccess(InvM_InvoiceListTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laphoadonnhieudongSuccess -->
      </class> <!-- tests.InvM_InvoiceListTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
